---
- name: install percona server apt-key
  apt_key:
    keyserver: "{{ percona_mysql_key_server }}"
    id: 9334A25F8507EFA5
    state: present

- name: install percona repo on debian family hosts
  apt_repository:
    repo: "{{ item }}"
    state: present
  register: percona_mysql_apt_repo
  loop: "{{ percona_mysql_repo|default([]) }}"

- name: update apt cache
  apt:
    update_cache: yes
  when: percona_mysql_apt_repo.changed
