---
- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: install_redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'
