- name: Add mongodb metrics
  command: >-
            /usr/sbin/pmm-admin add mongodb:metrics {{ pmm_alias | default(inventory_hostname) }}
            --uri "{{ pmm_mongodb_username }}:{{ pmm_mongodb_passwd }}@{{ pmm_mongodb_host | default('localhost') }}:{{ pmm_mongodb_port | default('27017') }}"
  when: ('mongodb:metrics' not in pmm_existing_services.stdout)
  register: mongodb_metrics

- name: Add mongodb QAN
  command: >-
            /usr/sbin/pmm-admin add mongodb:queries {{ pmm_alias | default(inventory_hostname) }}
            --uri "{{ pmm_mongodb_username }}:{{ pmm_mongodb_passwd }}@{{ pmm_mongodb_host | default('localhost') }}:{{ pmm_mongodb_port | default('27017') }}"
  when: ('mongodb:queries' not in pmm_existing_services.stdout)
  register: mongodb_queries

- name: Restart Prometheus client (MongoDB metrics)
  service:
    name: "pmm-mongodb-metrics-{{ mongodb_metrics_port }}"
    state: restarted
    enabled: yes
  when: (mongodb_metrics is defined and mongodb_metrics.changed) or (pmm_version_running is defined and pmm_version_running.changed)

- name: Restart MongoDB QAN
  command: "/usr/sbin/pmm-admin restart mongodb:queries {{ pmm_alias | default(inventory_hostname) }}"
  when: (mongodb_queries is defined and mongodb_queries.changed) or (pmm_version_running is defined and pmm_version_running.changed)
